apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
type: Opaque
data:
  aws_access_key: {{ .Values.aws_access_key | b64enc }}
  aws_secret_key: {{ .Values.aws_secret_key | b64enc }}
